#ifndef COLOURS_H_
#define COLOURS_H_

// HORIZONTALS
#define HORZ_THIN_SOLID "─"
#define HORZ_BOLD_SOLID "━"
#define HORZ_THIN_DASHED "┄"
#define HORZ_BOLD_DASHED "┅"
#define HORZ_THIN_DOTTED "┈"
#define HORZ_BOLD_DOTTED "┉"
#define HORZ_DOUBLE "═"

// VERTICALS
#define VERT_THIN_SOLID "│"
#define VERT_BOLD_SOLID "┃"
#define VERT_THIN_DASHED "┆"
#define VERT_BOLD_DASHED "┇"
#define VERT_THIN_DOTTED "┊"
#define VERT_BOLD_DOTTED "┋"
#define VERT_DOUBLE "║"	 

// TL
#define TL_THIN "┌"
#define TL_TOP_HEAVY "┍"
#define TL_SIDE_HEAVY "┎"
#define TL_BOLD "┏"
#define TL_TOP_DOUBLE "╒"
#define TL_SIDE_DOUBLE "╓"
#define TL_DOUBLE "╔"
#define TL_CURVED "╭"

// TR
#define TR_THIN "┐"
#define TR_TOP_HEAVY "┑"
#define TR_SIDE_HEAVY "┒"
#define TR_BOLD "┓"
#define TR_TOP_DOUBLE "╕"
#define TR_SIDE_DOUBLE "╖"
#define TR_DOUBLE "╗"
#define TR_CURVED "╮"

// BL
#define BL_THIN "└"
#define BL_TOP_HEAVY "┕"
#define BL_SIDE_HEAVY "┖"
#define BL_BOLD "┗"
#define BL_TOP_DOUBLE "╘"
#define BL_SIDE_DOUBLE "╙"
#define BL_DOUBLE "╚"
#define BL_CURVED "╰"

// BR
#define BR_THIN "┘"
#define BR_TOP_HEAVY "┙"
#define BR_SIDE_HEAVY "┚"
#define BR_BOLD "┛"
#define BR_TOP_DOUBLE "╛"
#define BR_SIDE_DOUBLE "╜"
#define BR_DOUBLE "╝"
#define BR_CURVED "╯"

// LEFT T
#define LEFT_T_THIN "├"
#define LEFT_T_MID_HEAVY "┝"
#define LEFT_T_TOP_HEAVY "┞"
#define LEFT_T_BOT_HEAVY "┟"
#define LEFT_T_TOP_BOT_HEAVY "┠"
#define LEFT_T_TOP_MID_HEAVY "┡"
#define LEFT_T_BOT_MID_HEAVY "┢"
#define LEFT_T_BOLD "┣"
#define LEFT_T_DOUBLE_HORZ "╞"
#define LEFT_T_DOUBLE_VERT "╟"
#define LEFT_T_DOUBLE_BOTH "╠"

// RIGHT T
#define RIGHT_T_THIN "┤"
#define RIGHT_T_MID_HEAVY "┥"
#define RIGHT_T_TOP_HEAVY "┦"
#define RIGHT_T_BOT_HEAVY "┧"
#define RIGHT_T_TOP_BOT_HEAVY "┨"
#define RIGHT_T_TOP_MID_HEAVY "┩"
#define RIGHT_T_BOT_MID_HEAVY "┪"
#define RIGHT_T_BOLD "┫"
#define RIGHT_T_DOUBLE_HORZ "╡"
#define RIGHT_T_DOUBLE_VERT "╢"
#define RIGHT_T_DOUBLE_BOTH "╣"

// TOP T
#define TOP_T_THIN "┬"
#define TOP_T_LEFT_HEAVY "┭"
#define TOP_T_RIGHT_HEAVY "┮"
#define TOP_T_TOP_HEAVY "┯"
#define TOP_T_BOT_HEAVY "┰"
#define TOP_T_LEFT_BOT_HEAVY "┱"
#define TOP_T_RIGHT_BOT_HEAVY "┲"
#define TOP_T_BOLD "┳"
#define TOP_T_DOUBLE_HORZ "╤"
#define TOP_T_DOUBLE_VERT "╥"
#define TOP_T_DOUBLE_BOTH "╦"

// BOT T
#define BOT_T_THIN "┴"
#define BOT_T_LEFT_HEAVY "┵"
#define BOT_T_RIGHT_HEAVY "┶"
#define BOT_T_TOP_HEAVY "┷"
#define BOT_T_BOT_HEAVY "┸"
#define BOT_T_LEFT_BOT_HEAVY "┹"
#define BOT_T_RIGHT_BOT_HEAVY "┺"
#define BOT_T_BOLD "┻"
#define BOT_T_DOUBLE_HORZ "╧"
#define BOT_T_DOUBLE_VERT "╨"
#define BOT_T_DOUBLE_BOTH "╩"

// CROSS
#define CROSS_THIN "┼"
#define CROSS_LEFT "┽"
#define CROSS_RIGHT "┾"
#define CROSS_MID "┿"
#define CROSS_TOP "╀"
#define CROSS_BOT "╁"
#define CROSS_VERT "╂"
#define CROSS_LEFT_TOP "╃"
#define CROSS_RIGHT_TOP "╄"
#define CROSS_LEFT_BOT "╅"
#define CROSS_RIGHT_BOT "╆"
#define CROSS_MID_TOP "╇"
#define CROSS_MID_BOT "╈"
#define CROSS_LEFT_VERT "╉"
#define CROSS_RIGHT_VERT "╊"
#define CROSS_BOLD "╋"
#define CROSS_DOUBLE_HORZ "╪"
#define CROSS_DOUBLE_VERT "╫"
#define CROSS_DOUBLE_BOTH "╬"

// DIAG
#define DIAG_RIGHT "╱"
#define DIAG_LEFT "╲"
#define DIAG_CROSS "╳"

#define RESET_COLOUR "\e[0m"
#define BOLD "\x1B[1m"
#define BACKSPACE "\b"

#define BLACK "\e[30m"
#define RED "\e[31m"
#define GREEN "\e[32m"
#define YELLOW "\e[33m"
#define BLUE "\e[34m"
#define MAGENTA "\e[35m"
#define CYAN "\e[36m"
#define WHITE "\e[37m"

#define BRIGHT_BLACK "\e[30;1m"
#define BRIGHT_RED "\e[31;1m"
#define BRIGHT_GREEN "\e[32;1m"
#define BRIGHT_YELLOW "\e[33;1m"
#define BRIGHT_BLUE "\e[34;1m"
#define BRIGHT_MAGENTA "\e[35;1m"
#define BRIGHT_CYAN "\e[36;1m"
#define BRIGHT_WHITE "\e[37;1m"

#endif
